version: "3"

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${PIHOLE_SUBNET_IP}
          gateway: ${PIHOLE_GATEWAY_IP}
          ip_range: ${PIHOLE_IP_RANGE}

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: pihole
    domainname: exampledomain
    cap_add:
      - NET_ADMIN
    environment:
      VIRTUAL_HOST: pihole.exampledomain
      ServerIP: ${PIHOLE_IP}
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    networks:
      pihole_network:
        ipv4_address: ${PIHOLE_IP}
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 53/udp
      - 67/udp
      - 443/tcp
      - 53/tcp
      - 80/tcp
    volumes:
      - pihole-data:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: "${UID}:${GID}"
    restart: unless-stopped
    environment:
      - FB_BASEURL=/filebrowser
    ports:
      - 443:8080
    volumes:
      - ${PATH_TO_DISK}:/data
      - filebrowser-data:/config

volumes:
  portainer-data:
  pihole-data:
  pihole-dnsmasq:
  filebrowser-data:
