version: "3.9"

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      TZ: ${TIMEZONE}
    ports:
      - 80:80
      - 443:443
    volumes:
      - heimdall-data:/config

portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      VERSION: docker
    volumes:
      - plex-data:/config
      - ${PATH_TO_MOVIES}:/movies

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      ServerIP: ${PIHOLE_IP}
      TZ: ${TIMEZONE}
      VIRTUAL_HOST: ${PIHOLE_HOST}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    ports:
      - 8010:8010/tcp
      - 8010:8010/udp
      - 8008:8008/tcp
    volumes:
      - pihole-data:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN

volumes:
  heimdall-data:
  portainer-data:
  plex-data:
  pihole-data:
  pihole-dnsmasq:
