version: "3.9"

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      TZ: ${TIMEZONE}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_TO_DISK}/appdata/heimdall:/config

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      VERSION: docker
    volumes:
      - ${PATH_TO_DISK}/appdata/plex:/config
      - ${PATH_TO_DISK}/media/movies:/movies

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    environment:
      ServerIP: ${PIHOLE_IPADDRESS}
      TZ: ${TIMEZONE}
      VIRTUAL_HOST: ${PIHOLE_HOST}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      DNSMASQ_LISTENING: all
      DNS1: 127.0.0.1
      DNS2: 1.1.1.1
    volumes:
      - pihole-data:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN

volumes:
  portainer_data:
  pihole-data:
  pihole-dnsmasq:
