version: "3.9"

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${PIHOLE_SUBNET_IP}
          gateway: ${PIHOLE_GATEWAY_IP}

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      TZ: ${TIMEZONE}
    ports:
      - 8111:80
      - 443:443
    volumes:
      - ${PATH_TO_DISK}/appdata/heimdall:/config

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
      VERSION: docker
    volumes:
      - ${PATH_TO_DISK}/appdata/plex:/config
      - ${PATH_TO_MOVIES}:/movies

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      ServerIP: ${NAS_IP}
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    networks:
      pihole_network:
        ipv4_address: ${PIHOLE_IP}
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    volumes:
      - pihole-data:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN

volumes:
  portainer-data:
  pihole-data:
  pihole-dnsmasq:
