version: "3.3"

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${PIHOLE_SUBNET_IP}
          gateway: ${GATEWAY_IP}
          ip_range: ${PIHOLE_IP_RANGE}

services:
  heimdall:
    image: linuxserver/heimdall:2.5.6
    container_name: heimdall
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - heimdall-data:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: pihole
    domainname: exampledomain
    cap_add:
      - NET_ADMIN
    environment:
      VIRTUAL_HOST: pihole.exampledomain
      ServerIP: ${PIHOLE_IP}
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    networks:
      pihole_network:
        ipv4_address: ${PIHOLE_IP}
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 53/udp
      - 67/udp
      - 443/tcp
      - 53/tcp
      - 80/tcp
    volumes:
      - pihole-data:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: "${UID}:${GID}"
    restart: unless-stopped
    environment:
      - FB_BASEURL=/filebrowser
    ports:
      - 445:8080
    volumes:
      - ${PATH_TO_STORAGE}:/data
      - filebrowser-data:/config

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      VERSION: docker
    volumes:
      - plex-data:/config
      - ${PATH_TO_STORAGE}/Movies:/movies

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    environment:
      - OPENVPN_PROVIDER=${VPN_PROV}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - LOCAL_NETWORK=${TRSN_LOCAL_IP}
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - transmission-openvpn-data:/config
      - ${PATH_TO_STORAGE}/Downloads:/data
    ports:
      - 9091:9091

volumes:
  heimdall-data:
  portainer-data:
  pihole-data:
  pihole-dnsmasq:
  filebrowser-data:
  plex-data:
  transmission-openvpn-data:
